export enum NotificationErrors {
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
  INVALID_NOTIFICATION_DATA = 'INVALID_NOTIFICATION_DATA',
  NOTIFICATION_CREATION_FAILED = 'NOTIFICATION_CREATION_FAILED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
}
