export enum BookingErrors {
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  INVALID_BOOKING_DATA = 'INVALID_BOOKING_DATA',
  BOOKING_CREATION_FAILED = 'BOOKING_CREATION_FAILED',
  BOOKING_UPDATE_FAILED = 'BOOKING_UPDATE_FAILED',
  BOOKING_DELETE_FAILED = 'BOOKING_DELETE_FAILED',
  PACKAGE_NOT_AVAILABLE = 'PACKAGE_NOT_AVAILABLE',
  PACKAGE_NOT_FOUND = 'PACKAGE_NOT_FOUND',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  INVALID_BOOKING_STATUS = 'INVALID_BOOKING_STATUS',
  CANNOT_CANCEL_BOOKING = 'CANNOT_CANCEL_BOOKING',
}
