export enum UserErrors {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_USER_DATA = 'INVALID_USER_DATA',
  USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
  USER_UPDATE_FAILED = 'USER_UPDATE_FAILED',
  USER_DELETE_FAILED = 'USER_DELETE_FAILED',
  USER_CREATION_FAILED = 'USER_CREATION_FAILED',
  INVALID_USER_ID = 'INVALID_USER_ID',
  USER_INACTIVE = 'USER_INACTIVE',
  UNAUTHORIZED_USER_ACCESS = 'UNAUTHORIZED_USER_ACCESS',
}
