export enum CustomerErrors {
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  CUSTOMER_ALREADY_EXISTS = 'CUSTOMER_ALREADY_EXISTS',
  INVALID_CUSTOMER_DATA = 'INVALID_CUSTOMER_DATA',
  CUSTOMER_CREATION_FAILED = 'CUSTOMER_CREATION_FAILED',
  CUSTOMER_UPDATE_FAILED = 'CUSTOMER_UPDATE_FAILED',
  CUSTOMER_DELETE_FAILED = 'CUSTOMER_DELETE_FAILED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
}
