export enum PaymentErrors {
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  INVALID_PAYMENT_DATA = 'INVALID_PAYMENT_DATA',
  PAYMENT_CREATION_FAILED = 'PAYMENT_CREATION_FAILED',
  PAYMENT_UPDATE_FAILED = 'PAYMENT_UPDATE_FAILED',
  PAYMENT_DELETE_FAILED = 'PAYMENT_DELETE_FAILED',
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  INSUFFICIENT_PAYMENT = 'INSUFFICIENT_PAYMENT',
  PAYMENT_ALREADY_COMPLETED = 'PAYMENT_ALREADY_COMPLETED',
}
