export enum PackageErrors {
  PACKAGE_NOT_FOUND = 'PACKAGE_NOT_FOUND',
  PACKAGE_ALREADY_EXISTS = 'PACKAGE_ALREADY_EXISTS',
  INVALID_PACKAGE_DATA = 'INVALID_PACKAGE_DATA',
  PACKAGE_CREATION_FAILED = 'PACKAGE_CREATION_FAILED',
  PACKAGE_UPDATE_FAILED = 'PACKAGE_UPDATE_FAILED',
  PACKAGE_DELETE_FAILED = 'PACKAGE_DELETE_FAILED',
  PACKAGE_NOT_AVAILABLE = 'PACKAGE_NOT_AVAILABLE',
  PACKAGE_FULL = 'PACKAGE_FULL',
}
