export enum DestinationErrors {
  DESTINATION_NOT_FOUND = 'DESTINATION_NOT_FOUND',
  DESTINATION_ALREADY_EXISTS = 'DESTINATION_ALREADY_EXISTS',
  INVALID_DESTINATION_DATA = 'INVALID_DESTINATION_DATA',
  DESTINATION_COUNTRY_ALREADY_EXISTS = 'DESTINATION_COUNTRY_ALREADY_EXISTS',
  DESTINATION_UPDATE_FAILED = 'DESTINATION_UPDATE_FAILED',
  DESTINATION_DELETE_FAILED = 'DESTINATION_DELETE_FAILED',
  DESTINATION_CREATION_FAILED = 'DESTINATION_CREATION_FAILED',
  INVALID_DESTINATION_ID = 'INVALID_DESTINATION_ID',
}
